### RAGAS

In [1]:
!uv --version

uv 0.12.17 (635500036 2026-09-18 x86_64-pc-windows-msvc)

In [2]:
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
import pandas as pd

df = pd.read_csv("data/ragas_synthetic_dataset.csv")
df.head(2)

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,What are the key components of the executive o...,"['1. 정책/법제 2. 기업/산업 3. 기술/연구 4. 인력/교육\n미국, 안전하...",The executive order signed by President Biden ...,AI Safety Researcher,WEB_SEARCH_LIKE,LONG,single_hop_specific_query_synthesizer
1,G7가 히로시마 AI 프로세스를 통해 AI 기업을 위한 국제 행동강령을 만든 이유는...,"['SPRi AI Brief |\n2023-12월호\nG7, 히로시마 AI 프로세스...",G7은 히로시마 AI 프로세스를 통해 AI 기업을 대상으로 AI 위험 식별과 완화를...,AI Governance Analyst,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer

In [4]:
from datasets import Dataset

test_dataset = Dataset.from_pandas(df)
test_dataset

Dataset({
    features: ['user_input', 'reference_contexts', 'reference', 'persona_name', 'query_style', 'query_length', 'synthesizer_name'],
    num_rows: 10
})

In [5]:
import ast

def convert_to_list(example):
    value = example["reference_contexts"]
    if isinstance(value, str):
        value = ast.literal_eval(value)

    if not isinstance(value, list):
        raise TypeError(f"reference_contexts must be a list, got {type(value).__name__}")

    return {"reference_contexts": value}

test_dataset = test_dataset.map(convert_to_list)

print(test_dataset["reference_contexts"])
print("---")
print(test_dataset[0]["reference_contexts"])

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Column([['1. 정책/법제 2. 기업/산업 3. 기술/연구 4. 인력/교육\n미국, 안전하고 신뢰할 수 있는 AI 개발과 사용에 관한 행정명령 발표\nKEY Contents\nn 미국 바이든 대통령이 ‘안전하고 신뢰할 수 있는 AI 개발과 사용에 관한 행정명령’에 서명하고\n광범위한 행정 조치를 명시\nn 행정명령은 △AI의 안전과 보안 기준 마련 △개인정보보호 △형평성과 시민권 향상 △소비자\n보호 △노동자 지원 △혁신과 경쟁 촉진 △국제협력을 골자로 함\n£바이든 대통령, AI 행정명령 통해 안전하고 신뢰할 수 있는 AI 개발과 활용 추진\nn 미국 바이든 대통령이 2023년 10월 30일 연방정부 차원에서 안전하고 신뢰할 수 있는 AI 개발과\n사용을 보장하기 위한 행정명령을 발표\n∙ 행정명령은 △AI의 안전과 보안 기준 마련 △개인정보보호 △형평성과 시민권 향상 △소비자 보호\n△노동자 지원 △혁신과 경쟁 촉진 △국제협력에 관한 내용을 포괄\nn (AI 안전과 보안 기준) 강력한 AI 시스템을 개발하는 기업에게 안전 테스트 결과와 시스템에 관한\n주요 정보를 미국 정부와 공유할 것을 요구하고, AI 시스템의 안전성과 신뢰성 확인을 위한 표준 및\nAI 생성 콘텐츠 표시를 위한 표준과 모범사례 확립을 추진\n∙ △1026 플롭스(FLOPS, Floating Point Operation Per Second)를 초과하는 컴퓨팅 성능 또는 생물학적\n서열 데이터를 주로 사용하고 1023플롭스를 초과하는 컴퓨팅 성능을 사용하는 모델 △단일 데이터센터에서\n1,000Gbit/s 이상의 네트워킹으로 연결되며 AI 훈련에서 이론상 최대 1020 플롭스를 처리할 수 있는\n컴퓨팅 용량을 갖춘 컴퓨팅 클러스터가 정보공유 요구대상\nn (형평성과 시민권 향상) 법률, 주택, 보건 분야에서 AI의 무책임한 사용으로 인한 차별과 편견 및 기타\n문제를 방지하는 조치를 확대\n∙ 형사사법 시스템에서 AI 사용 모범사례를 개발하고, 주택 임대 시 AI 알고리즘 차별을 막기 위한 명확한\n지침을 제공하며, 보건복지 부문에서 책임 있는 AI 배포와 사용을 위한 전략을 마련\nn (소비자 보호와 근로자 지원) 의료 분야에서 책임 있는 AI 사용을 촉진하고 맞춤형 개인교습 등 학교\n내 AI 교육 도구 관련 자원을 개발하며, AI로 인한 근로자 피해를 완화하고 이점을 극대화하는 원칙과\n모범사례를 마련\nn (혁신과 경쟁 촉진) 국가AI연구자원(National Artificial Intelligence Research Resource, NAIRR)*을\n통해 미국 전역의 AI 연구를 촉진하고, 중소기업과 개발자에 기술과 인프라를 지원\n* 국가 차원에서 AI 연구 인프라를 확충해 더 많은 AI 연구자에게 인프라를 지원하는 프로그램\n∙ 비자 기준과 인터뷰 절차의 현대화와 간소화로 AI 관련 주요 분야의 전문 지식을 갖춘 외국인들이 미국에서\n공부하고 취업할 수 있도록 지원\n☞ 출처 : The White House, Executive Order on the Safe, Secure, and Trustworthy Development and Use of\nArtificial Intelligence (E.O. 14110), 2023.10.30.\n'], ['SPRi AI Brief |\n2023-12월호\nG7, 히로시마 AI 프로세스를 통해 AI 기업 대상 국제 행동강령에 합의\nKEY Contents\nn G7이 첨단 AI 시스템을 개발하는 기업을 대상으로 AI 위험 식별과 완화를 위해 자발적인\n채택을 권고하는 AI 국제 행동강령을 마련\nn 행동강령은 AI 수명주기 전반에 걸친 위험 평가와 완화, 투명성과 책임성의 보장, 정보공유와\n이해관계자 간 협력, 보안 통제, 콘텐츠 인증과 출처 확인 등의 조치를 요구\n£G7, 첨단 AI 시스템의 위험 관리를 위한 국제 행동강령 마련\nn 주요 7개국(G7)*은 2023년 10월 30일 ‘히로시마 AI 프로세스’를 통해 AI 기업 대상의 AI 국제\n행동강령(International Code of Conduct for Advanced AI Systems)에 합의\n∙ G7은 2023년 5월 일본 히로시마에서 개최된 정상회의에서 생성 AI에 관한 국제규범 마련과\n정보공유를 위해 ‘히로시마 AI 프로세스’를 출범**\n∙ 기업의 자발적 채택을 위해 마련된 이번 행동강령은 기반모델과 생성 AI를 포함한 첨단 AI 시스템의\n위험 식별과 완화에 필요한 조치를 포함\n* 주요 7개국(G7)은 미국, 일본, 독일, 영국, 프랑스, 이탈리아, 캐나다를 의미\n** 5월 정상회의에는 한국, 호주, 베트남 등을 포함한 8개국이 초청을 받았으나, AI 국제 행동강령에는 우선 G7 국가만 포함하여 채택\nn G7은 행동강령을 통해 아래의 조치를 제시했으며, 빠르게 발전하는 기술에 대응할 수 있도록\n이해관계자 협의를 통해 필요에 따라 개정할 예정\n∙ 첨단 AI 시스템의 개발 과정에서 AI 수명주기 전반에 걸쳐 위험을 평가 및 완화하는 조치를 채택하고,\n첨단 AI 시스템의 출시와 배포 이후 취약점과 오용 사고, 오용 유형을 파악해 완화\n∙ 첨단 AI 시스템의 성능과 한계를 공개하고 적절하거나 부적절한 사용영역을 알리는 방법으로 투명성을\n보장하고 책임성을 강화\n∙ 산업계, 정부, 시민사회, 학계를 포함해 첨단 AI 시스템을 개발하는 조직 간 정보공유와 사고 발생 시\n신고를 위해 협력하고, 위험 기반 접근방식을 토대로 개인정보보호 정책과 위험 완화 조치를 포함하는\nAI 거버넌스와 위험 관리 정책을 마련\n∙ AI 수명주기 전반에 걸쳐 물리보안, 사이버보안, 내부자 위협 보안을 포함한 강력한 보안 통제 구현\n∙ 사용자가 AI 생성 콘텐츠를 식별할 수 있도록 워터마크를 비롯하여 기술적으로 가능한 기법으로\n신뢰할 수 있는 콘텐츠 인증과 출처 확인 메커니즘을 개발 및 구축\n∙ 사회적 위험과 안전·보안 문제를 완화하는 연구와 효과적인 완화 대책에 우선 투자하고, 기후 위기\n대응, 세계 보건과 교육 등 세계적 난제 해결을 위한 첨단 AI 시스템을 우선 개발\n∙ 국제 기술 표준의 개발 및 채택을 가속화하고, 개인정보와 지식재산권 보호를 위해 데이터 입력과 수집\n시 적절한 보호 장치 구현\n☞ 출처: G7, Hiroshima Process International Code of Conduct for Advanced AI Systems, 2023.10.30.\n2\n'], ['1. 정책/법제 2. 기업/산업 3. 기술/연구 4. 인력/교육\n영국 AI 안전성 정상회의에 참가한 28개국, AI 위험에 공동 대응 선언\nKEY Contents\nn 영국 블레츨리 파크에서 개최된 AI 안전성 정상회의에 참가한 28개국들이 AI 안전 보장을\n위한 협력 방안을 담은 블레츨리 선언을 발표\nn 첨단 AI를 개발하는 국가와 기업들은 AI 시스템에 대한 안전 테스트 계획에 합의했으며,\n영국의 AI 안전 연구소가 전 세계 국가와 협력해 테스트를 주도할 예정\n£AI 안전성 정상회의 참가국들, 블레츨리 선언 통해 AI 안전 보장을 위한 협력에 합의\nn 2023년 11월 1~2일 영국 블레츨리 파크에서 열린 AI 안전성 정상회의(AI Safety Summit)에\n참가한 28개국 대표들이 AI 위험 관리를 위한 ‘블레츨리 선언’을 발표\n∙ 선언은 AI 안전 보장을 위해 국가, 국제기구, 기업, 시민사회, 학계를 포함한 모든 이해관계자의 협력이\n중요하다고 강조했으며, 특히 최첨단 AI 시스템 개발 기업은 안전 평가를 비롯한 적절한 조치를 취하여\nAI 시스템의 안전을 보장할 책임이 있다고 지적\n∙ 각국은 AI 안전 보장을 위해 첨단 AI 개발기업의 투명성 향상, 적절한 평가지표와 안전 테스트 도구\n개발, 공공부문 역량 구축과 과학 연구개발 등의 분야에서 협력하기로 합의\n£영국 총리, 정부 주도의 첨단 AI 시스템 안전 테스트 계획 발표\nn 리시 수낙 영국 총리는 AI 안전성 정상회의를 마무리하며 첨단 AI 모델에 대한 안전성 시험 계획\n수립과 테스트 수행을 주도할 영국 AI 안전 연구소의 출범을 발표\n∙ 첨단 AI 모델의 안전 테스트는 국가 안보와 안전, 사회적 피해를 포함한 여러 잠재적 유해 기능에 대한\n시험을 포함하며, 참석자들은 정부 주도의 외부 안전 테스트에 합의\n∙ 각국 정부는 테스트와 기타 안전 연구를 위한 공공부문 역량에 투자하고, 테스트 결과가 다른 국가와\n관련된 경우 해당 국가와 결과를 공유하며, 적절한 시기에 공동 표준 개발을 위해 노력하기로 합의\nn 참가국들은 튜링상을 수상한 AI 학자인 요슈아 벤지오 교수가 주도하는 ‘과학의 현황(State of\nthe Science)’ 보고서 작성에도 합의했으며, 보고서를 통해 첨단 AI의 위험과 가능성에 관한\n기존 연구를 과학적으로 평가하고 향후 AI 안전 연구를 위한 우선순위를 제시할 계획\nn 한국은 영국 정부와 6개월 뒤에 온라인으로 AI 미니 정상회의를 공동 개최하기로 합의했으며,\n프랑스 정부와는 1년 후 대면 정상회의를 개최할 예정\n☞ 출처: Gov.uk, The Bletchley Declaration by Countries Attending the AI Safety Summit, 1-2 November 2023, 2023.11.01.\nGov.uk, World leaders, top AI companies set out plan for safety testing of frontier as first global AI Safety Summit\nconcludes, 2023.11.02.\n'], ['SPRi AI Brief |\n2023-12월호\n미국 법원, 예술가들이 생성 AI 기업에 제기한 저작권 소송 기각\nKEY Contents\nn 미국 캘리포니아 북부지방법원은 미드저니, 스태빌리티AI, 디비언트아트를 대상으로 예술가\n3인이 제기한 저작권 침해 소송을 기각\nn 법원은 기각 이유로 고소장에 제시된 상당수 작품이 저작권청에 등록되지 않았으며, AI로\n생성된 이미지와 특정 작품 간 유사성을 입증하기 어렵다는 점을 제시\n£예술가들의 AI 저작권 침해 소송, 저작권 미등록과 증거불충분으로 기각\nn 미국 캘리포니아 북부지방법원의 윌리엄 오릭(William Orrick) 판사는 2023년 10월 30일 미드저니\n(Midjourney), 스태빌리티AI(Stability AI), 디비언트아트(DeviantArt)에 제기된 저작권 침해 소송을 기각\n∙ 2023년 1월 예술가 사라 앤더슨(Sarah Anderson), 캘리 맥커넌(Kelly McKernan), 칼라\n오르티즈(Karla Ortiz)는 이미지 생성 AI 서비스를 개발한 3개 기업을 상대로 저작권 침해 소송을 제기\n∙ 예술가들은 3개 기업이 AI 모델을 학습시키기 위해 원작자 동의 없이 작품을 학습 데이터셋에\n포함하여 저작권을 침해했다고 주장했으며, 법원은 지난 4월 피소 기업들이 제출한 기각 신청을\n수용해 소송을 기각\nn 오릭 판사는 판결문에서 소송을 기각한 핵심 이유로 예술가들의 저작권 미등록을 제시\n∙ 판결문은 소송을 제기한 캘리 맥커넌과 칼라 오르티즈가 미국 저작권청에 예술 작품에 대한 저작권을\n제출하지 않았다는 점을 지적했으며, 사라 앤더슨은 고소장에 인용된 수백 개의 작품 중 16개 작품에\n대해서만 저작권을 보유\nn 판결문은 또한 생성 AI 모델 훈련에 사용된 모든 이미지에 저작권이 있다거나, 생성 AI로 만든\n이미지가 저작물을 이용해 훈련되었으므로 저작물의 파생 이미지라는 주장은 개연성이 부족하다고\n지적\n∙ AI는 새로운 이미지를 생성할 때 다양한 예술가의 작품을 참조하므로, 생성된 이미지와 저작권을 가진\n특정 작품과의 실질적 유사성을 입증할 수 없다면 저작권 침해를 인정받기 어려움\nn 오릭 판사는 원고 측에 고소장을 수정하고 저작권이 침해된 특정 이미지를 중심으로 소송 범위를\n줄여 소송을 다시 제기할 것을 요청\n∙ 단, 사라 앤더슨이 저작권을 보유한 16개 작품을 무단으로 복제한 스태빌리티AI에 대한 저작권 침해\n소송은 인정되어 계속 진행됨\n☞ 출처: Venturebeat, Midjourney, Stability AI and DeviantArt win a victory in copyright case by artists- but the\nfight continues, 2023.10.30.\n4\n'], ['1. 정책/법제 2. 기업/산업 3. 기술/연구 4. 인력/교육\n미국 연방거래위원회, 저작권청에 소비자 보호와 경쟁 측면의 AI 의견서 제출\nKEY Contents\nn 미국 FTC는 저작권청이 실시한 저작권과 AI 관련 질의공고에 대하여 소비자 보호와 경쟁\n측면의 의견을 제시\nn FTC는 생성 AI로 인한 창작자와 소비자 피해의 가능성에 우려를 표시하는 한편, 일부\n빅테크가 막대한 재원을 활용해 시장 지배력을 더욱 강화할 수 있다는 우려를 제기\n£FTC, 생성 AI로 인한 소비자와 창작자의 피해 및 빅테크의 시장 지배력 강화 우려\nn 미국 연방거래위원회(FTC)가 2023년 10월 30일 저작권청(U.S. Copyright Office, USCO)이\n지난 9월 발표한 저작권과 AI 관련 질의공고(Notice of Inquiry, NOI)에 대한 의견서를 발표\n∙ 저작권청은 생성 AI와 관련된 저작권법과 정책 이슈를 조사하고 있으며, 폭넓은 의견 수렴을 통해\n입법과 규제 조치의 필요성을 검토할 계획\n∙ FTC는 생성 AI의 개발과 배포가 소비자, 근로자, 중소기업에 피해를 줄 수 있다며 소비자의 개인정보\n침해, 차별과 편견의 자동화, 사기 범죄 등 AI 사용과 관련된 위험에 주목\nn FTC는 저작권법에 따른 권리와 책임 범위를 넘어서는 저작권 문제에 주목하여 생성 AI로 인해\n창작자의 경쟁력이 불공정한 피해를 볼 수 있으며, 소비자가 특정 창작자의 작품을 생성 AI가\n만들었다고 오해할 소지가 있다고 지적\n∙ 저작권법에 저촉되는 행위는 불공정 경쟁이나 기만행위에도 해당될 수 있으며, 창작자의 평판 악화,\n저작물의 가치 저하나 개인정보 유출로 소비자에 상당한 피해를 초래 가능\nn FTC는 일부 빅테크가 막대한 재원을 활용해 생성 AI 사용자의 이탈을 막고 저작권이 있는 상용\n데이터에 대한 독점 라이선스를 확보해 시장 지배력을 더욱 강화할 수 있다는 우려도 제기\n∙ 이와 관련 FTC는 아마존 AI 비서 ‘알렉사(Alexa)’와 스마트홈 보안 기기 ‘링(Ring)’이 소비자의 사적\n정보를 알고리즘 훈련에 사용하여 프라이버시를 침해한 혐의를 조사하는 등 법적 권한을 활용해 AI\n관련 불법 행위에 대처하고 있음\n* FTC는 2023년 5월 31일 동의를 받지 않고 어린이들의 음성과 위치 정보를 활용한 ‘알렉사’와 고객의 사적 영상에 대하여\n직원에게 무제한 접근 권한을 부여한 ‘링’에 3,080만 달러(약 420억 원)의 과징금을 부과\nn FTC는 빠르게 발전하는 생성 AI가 여러 산업과 비즈니스에 변화를 가져올 수 있지만, 현행법상\nAI에 관한 예외 조항은 없다며, 모든 권한을 활용해 소비자를 보호하고 개방적이고 공정한 경쟁\n시장을 유지하겠다고 강조\n☞ 출처: FTC, In Comment Submitted to U.S. Copyright Office, FTC Raises AI-related Competition and\nConsumer Protection Issues, Stressing That It Will Use Its Authority to Protect Competition and\nConsumers in AI Markets, 2023.10.30.\n'], ...])
---
['1. 정책/법제 2. 기업/산업 3. 기술/연구 4. 인력/교육\n미국, 안전하고 신뢰할 수 있는 AI 개발과 사용에 관한 행정명령 발표\nKEY Contents\nn 미국 바이든 대통령이 ‘안전하고 신뢰할 수 있는 AI 개발과 사용에 관한 행정명령’에 서명하고\n광범위한 행정 조치를 명시\nn 행정명령은 △AI의 안전과 보안 기준 마련 △개인정보보호 △형평성과 시민권 향상 △소비자\n보호 △노동자 지원 △혁신과 경쟁 촉진 △국제협력을 골자로 함\n£바이든 대통령, AI 행정명령 통해 안전하고 신뢰할 수 있는 AI 개발과 활용 추진\nn 미국 바이든 대통령이 2023년 10월 30일 연방정부 차원에서 안전하고 신뢰할 수 있는 AI 개발과\n사용을 보장하기 위한 행정명령을 발표\n∙ 행정명령은 △AI의 안전과 보안 기준 마련 △개인정보보호 △형평성과 시민권 향상 △소비자 보호\n△노동자 지원 △혁신과 경쟁 촉진 △국제협력에 관한 내용을 포괄\nn (AI 안전과 보안 기준) 강력한 AI 시스템을 개발하는 기업에게 안전 테스트 결과와 시스템에 관한\n주요 정보를 미국 정부와 공유할 것을 요구하고, AI 시스템의 안전성과 신뢰성 확인을 위한 표준 및\nAI 생성 콘텐츠 표시를 위한 표준과 모범사례 확립을 추진\n∙ △1026 플롭스(FLOPS, Floating Point Operation Per Second)를 초과하는 컴퓨팅 성능 또는 생물학적\n서열 데이터를 주로 사용하고 1023플롭스를 초과하는 컴퓨팅 성능을 사용하는 모델 △단일 데이터센터에서\n1,000Gbit/s 이상의 네트워킹으로 연결되며 AI 훈련에서 이론상 최대 1020 플롭스를 처리할 수 있는\n컴퓨팅 용량을 갖춘 컴퓨팅 클러스터가 정보공유 요구대상\nn (형평성과 시민권 향상) 법률, 주택, 보건 분야에서 AI의 무책임한 사용으로 인한 차별과 편견 및 기타\n문제를 방지하는 조치를 확대\n∙ 형사사법 시스템에서 AI 사용 모범사례를 개발하고, 주택 임대 시 AI 알고리즘 차별을 막기 위한 명확한\n지침을 제공하며, 보건복지 부문에서 책임 있는 AI 배포와 사용을 위한 전략을 마련\nn (소비자 보호와 근로자 지원) 의료 분야에서 책임 있는 AI 사용을 촉진하고 맞춤형 개인교습 등 학교\n내 AI 교육 도구 관련 자원을 개발하며, AI로 인한 근로자 피해를 완화하고 이점을 극대화하는 원칙과\n모범사례를 마련\nn (혁신과 경쟁 촉진) 국가AI연구자원(National Artificial Intelligence Research Resource, NAIRR)*을\n통해 미국 전역의 AI 연구를 촉진하고, 중소기업과 개발자에 기술과 인프라를 지원\n* 국가 차원에서 AI 연구 인프라를 확충해 더 많은 AI 연구자에게 인프라를 지원하는 프로그램\n∙ 비자 기준과 인터뷰 절차의 현대화와 간소화로 AI 관련 주요 분야의 전문 지식을 갖춘 외국인들이 미국에서\n공부하고 취업할 수 있도록 지원\n☞ 출처 : The White House, Executive Order on the Safe, Secure, and Trustworthy Development and Use of\nArtificial Intelligence (E.O. 14110), 2023.10.30.\n']

In [ ]:
# !uv add pymupdf

In [ ]:
# !uv add faiss-cpu

In [10]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

loader = PyMuPDFLoader("data/SPRI_AI_Brief_2023년12월호_F.pdf")
docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=50)
split_documents = text_splitter.split_documents(docs)

embeddings = OpenAIEmbeddings()

vectorstore = FAISS.from_documents(documents=split_documents, embedding=embeddings)

retriever = vectorstore.as_retriever()

prompt = PromptTemplate.from_template(
    """You are an assistant for question-answering tasks. 
Use the following pieces of retrieved context to answer the question. 
If you don't know the answer, just say that you don't know. 

#Context: 
{context}

#Question:
{question}

#Answer:"""
)

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
    |StrOutputParser()
)

In [11]:
batch_dataset = list(test_dataset["user_input"])
batch_dataset[:3]

['What are the key components of the executive order signed by President Biden on October 30, 2023, regarding the development and use of safe and trustworthy AI?',
 'G7가 히로시마 AI 프로세스를 통해 AI 기업을 위한 국제 행동강령을 만든 이유는 뭐고, 그 내용은 어떤거야?',
 '프랑스는 AI 안전성 정상회의에서 어떤 역할을 할 것인가요?']

In [12]:
retrieved_documents = retriever.batch(batch_dataset)
retrieved_contexts = [
    [doc.page_content for doc in documents]
    for documents in retrieved_documents
]

responses = chain.batch(batch_dataset)
responses

['The key components of the executive order signed by President Biden on October 30, 2023, regarding the development and use of safe and trustworthy AI include:\n\n1. Establishing safety and security standards for AI.\n2. Ensuring privacy protection.\n3. Enhancing equity and civil rights.\n4. Protecting consumers.\n5. Supporting workers.\n6. Promoting innovation and competition.\n7. Encouraging international cooperation.\n\nThe order requires companies developing powerful AI systems to share safety test results and key information with the U.S. government, and it aims to establish standards for the safety and reliability of AI systems, as well as for labeling AI-generated content.',
 'G7는 히로시마 AI 프로세스를 통해 AI 기업을 위한 국제 행동강령을 만든 이유는 첨단 AI 시스템의 개발과 관련된 위험을 식별하고 완화하기 위해 자발적인 채택을 권고하기 위함입니다. 이 행동강령은 AI 수명주기 전반에 걸친 위험 평가와 완화, 투명성과 책임성의 보장, 정보 공유와 이해관계자 간 협력, 보안 통제, 콘텐츠 인증과 출처 확인 등의 조치를 요구합니다.\n\n주요 내용은 다음과 같습니다:\n- AI 시스템의 개발 과정에서 위험을 평가하고 완화하는 조치를 채택\n- AI 시스템의 성능과 한계를 공개하고 적절한 사용 영역을 알리는 방법으로 투명성을 보장\n- 산업계, 정부, 시민사회, 학계 간의 정보 공유 및 협력\n- 강력한 보안 통제 구현\n- AI 생성 콘텐츠의 신뢰성을 높이기 위한 인증 및 출처 확인 메커니즘 개발\n- 사회적 위험과 안전 문제를 완화하기 위한 연구 및 투자 우선순위 설정\n- 국제 기술 표준의 개발 및 개인정보 보호를 위한 적절한 보호 장치 구현',
 '프랑스는 AI 안전성 정상회의에서 1년 후 대면 정상회의를 개최할 예정입니다.',
 '사라 앤더슨은 저작권 소송에서 원고 중 한 명으로, 미드저니, 스태빌리티AI, 디비언트아트에 대해 저작권 침해를 주장했습니다. 그녀는 AI 모델이 자신의 작품을 원작자 동의 없이 학습 데이터셋에 포함시켜 저작권을 침해했다고 주장했으며, 고소장에 인용된 수백 개의 작품 중 16개 작품에 대해서만 저작권을 보유하고 있었습니다. 법원은 그녀의 소송을 기각했지만, 스태빌리티AI에 대한 저작권 침해 소송은 계속 진행될 수 있도록 인정되었습니다.',
 "FTC는 2023년 5월 31일에 동의를 받지 않고 어린이들의 음성과 위치 정보를 활용한 '알렉사'와 고객의 사적 영상에 대하여 직원에게 무제한 접근 권한을 부여한 '링'에 대해 3,080만 달러(약 420억 원)의 과징금을 부과했습니다.",
 "Aleph Alpha, a prominent AI company in Germany, is actively involved in lobbying against regulations related to foundation models in the EU's AI Act negotiations. The company has been pressuring the German government to oppose all types of regulations on foundation models, expressing concerns that such regulations could hinder their competitiveness compared to companies in the U.S. and China.",
 "The main objectives of the AI 안전 기금 (AI Safety Fund) established by the Frontier Model Forum include:\n\n1. Supporting research on AI safety by providing funding for activities that help discover and validate vulnerabilities in AI models.\n2. Developing new model evaluation techniques specifically for red team activities, which are aimed at identifying and mitigating risks associated with advanced AI systems.\n3. Addressing the gap in AI safety research, particularly in light of the rapid advancements in AI technology.\n4. Facilitating collaboration among industry, government, civil society, and academia to share information and report incidents related to AI systems.\n5. Promoting the evaluation of external research groups' AI systems to enhance safety and security measures.",
 'MIT is one of the 12 institutions that collaborated with Cohere to launch the Data Provenance Explorer platform. This platform aims to enhance data transparency by providing information about the original data sources, re-licensing status, authorship, and other attributes of datasets used in AI model training.',
 '통이치엔원 2.0의 주요 성능 향상은 복잡한 지침 이해, 광고문구 작성, 추론, 암기 등에서의 개선입니다. 이 모델은 언어 이해 테스트(MMLU), 수학(GSM8k), 질문 답변(ARC-C)과 같은 벤치마크 테스트에서 라마(Llama-2-70B)와 GPT-3.5를 비롯한 주요 AI 모델을 능가하는 성능을 보입니다.',
 '삼성 가우스는 삼성전자가 개발한 생성형 AI 모델로, 언어, 코드, 이미지의 세 가지 모델로 구성되어 있습니다. 이 AI는 온디바이스에서 작동할 수 있도록 설계되어 있어 사용자 정보가 외부로 유출될 위험이 없다는 장점이 있습니다. 삼성전자는 이 모델을 다양한 제품에 단계적으로 탑재할 계획을 가지고 있으며, 텍스트 생성, 코드 생성, 이미지 생성 등의 기능을 지원합니다.']

In [15]:
for column_name, values in {
    "retrieved_contexts": retrieved_contexts,
    "response": responses,
}.items():
    if column_name in test_dataset.column_names:
        test_dataset = test_dataset.remove_columns(column_name)
    test_dataset = test_dataset.add_column(column_name, values)

print(test_dataset.column_names)
test_dataset.select_columns([
    "user_input", "retrieved_contexts", "responses", "reference"
])

['user_input', 'reference_contexts', 'reference', 'persona_name', 'query_style', 'query_length', 'synthesizer_name', 'responses', 'retrieved_contexts', 'response']

Dataset({
    features: ['user_input', 'retrieved_contexts', 'responses', 'reference'],
    num_rows: 10
})

In [16]:
from ragas import RunConfig, evaluate
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.llms import LangchainLLMWrapper
from ragas.metrics import(
    AnswerRelevancy,
    Faithfulness,
    LLMContextPrecisionWithReference,
    LLMContextRecall,
)

evaluator_llm = LangchainLLMWrapper(
    ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0,
        timeout=60,
        max_retries=1,
    )
)
evaluator_embeddings = LangchainEmbeddingsWrapper(
    OpenAIEmbeddings(
        model="text-embedding-3-small",
        timeout=60,
        max_retries=1,
    )
)

metrics = [
    Faithfulness(),
    AnswerRelevancy(strictness=1),
    LLMContextPrecisionWithReference(),
    LLMContextRecall(),
]

result = evaluate(
    dataset=test_dataset,
    metrics=metrics,
    llm=evaluator_llm,
    embeddings=evaluator_embeddings,
    run_config=RunConfig(
        timeout=60,
        max_retries=2,
        max_wait=10,
        max_workers=4,
    ),
    batch_size=2,
    raise_exceptions=True,
)

result

C:\Users\user\AppData\Local\Temp\ipykernel_4544\1899244835.py:4: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import(
C:\Users\user\AppData\Local\Temp\ipykernel_4544\1899244835.py:4: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import(
C:\Users\user\AppData\Local\Temp\ipykernel_4544\1899244835.py:4: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import(
C:\Users\user\AppData\Local\Temp\ipykernel_4544\1899244835.py:4: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import(
C:\Users\user\AppData\Local\Temp\ipykernel_4544\1899244835.py:11: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(
C:\Users\user\AppData\Local\Temp\ipykernel_4544\1899244835.py:19: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = LangchainEmbeddingsWrapper(

Evaluating:   0%|          | 0/40 [00:00<?, ?it/s]

Batch 1/20:   0%|          | 0/2 [00:00<?, ?it/s]

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-100' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-101' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\urllib3\connectionpool.py:848: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-101' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-103' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-104' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-104' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-106' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-107' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-107' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-120' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-121' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\contextlib.py:132: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __enter__(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-121' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-135' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-136' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\threading.py:293: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  self._waiters = _deque()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-136' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-141' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-142' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-142' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-161' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-162' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\encodings\idna.py:172: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  if not (0 < len(label) < 64):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-162' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-192' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-193' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\pydantic\main.py:253: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __init__(self, /, **data: Any) -> None:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-193' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000001B3C4E127C0> is already entered
Task was destroyed but it is pending!
task: <Task pending name='Task-208' coro=<_async_in_context.<locals>.run_in_context() done, defined at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-209' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\tenacity\__init__.py:381: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  self._add_action_func(lambda rs: DoAttempt())
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-209' coro=<Kernel.shell_main() running at d:\hanhwa0902\rag_two_branch\.venv\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

{'faithfulness': 0.8333, 'answer_relevancy': 0.7231, 'llm_context_precision_with_reference': 0.9250, 'context_recall': 0.9750}

In [17]:
result_df = result.to_pandas()
result_df.head()

,user_input,retrieved_contexts,reference_contexts,response,reference,persona_name,query_style,query_length,faithfulness,answer_relevancy,llm_context_precision_with_reference,context_recall
0,What are the key components of the executive o...,[1. 정책/법제 \n2. 기업/산업 \n3. 기술/연구 \n 4. 인력/교육\n...,"[1. 정책/법제 2. 기업/산업 3. 기술/연구 4. 인력/교육\n미국, 안전하고...",The key components of the executive order sign...,The executive order signed by President Biden ...,AI Safety Researcher,WEB_SEARCH_LIKE,LONG,1.000000,0.924848,1.00,0.75
1,G7가 히로시마 AI 프로세스를 통해 AI 기업을 위한 국제 행동강령을 만든 이유는...,"[SPRi AI Brief | \n2023-12월호\n2\nG7, 히로시마 AI ...","[SPRi AI Brief |\n2023-12월호\nG7, 히로시마 AI 프로세스를...",G7는 히로시마 AI 프로세스를 통해 AI 기업을 위한 국제 행동강령을 만든 이유는...,G7은 히로시마 AI 프로세스를 통해 AI 기업을 대상으로 AI 위험 식별과 완화를...,AI Governance Analyst,POOR_GRAMMAR,LONG,1.000000,0.635504,1.00,1.00
2,프랑스는 AI 안전성 정상회의에서 어떤 역할을 할 것인가요?,[1. 정책/법제 \n2. 기업/산업 \n3. 기술/연구 \n 4. 인력/교육\n...,[1. 정책/법제 2. 기업/산업 3. 기술/연구 4. 인력/교육\n영국 AI 안전...,프랑스는 AI 안전성 정상회의에서 1년 후 대면 정상회의를 개최할 예정입니다.,프랑스 정부는 1년 후 대면 정상회의를 개최할 예정입니다.,AI Safety Researcher,POOR_GRAMMAR,LONG,0.000000,0.544051,0.50,1.00
3,사라 앤더슨이 저작권 소송에서 어떤 역할을 했는지 설명해 주세요.,"[SPRi AI Brief | \n2023-12월호\n4\n미국 법원, 예술가들이...","[SPRi AI Brief |\n2023-12월호\n미국 법원, 예술가들이 생성 A...","사라 앤더슨은 저작권 소송에서 원고 중 한 명으로, 미드저니, 스태빌리티AI, 디비...","사라 앤더슨은 2023년 1월에 미드저니, 스태빌리티AI, 디비언트아트를 상대로 저...",AI Governance Analyst,MISSPELLED,LONG,0.833333,0.382584,1.00,1.00
4,FTC는 2023년 5월 31일에 어떤 조치를 취했나요?,[데이터에 대한 독점 라이선스를 확보해 시장 지배력을 더욱 강화할 수 있다는 우려도...,[1. 정책/법제 2. 기업/산업 3. 기술/연구 4. 인력/교육\n미국 연방거래위...,FTC는 2023년 5월 31일에 동의를 받지 않고 어린이들의 음성과 위치 정보를 ...,FTC는 2023년 5월 31일 동의를 받지 않고 어린이들의 음성과 위치 정보를 활...,AI Safety Researcher,POOR_GRAMMAR,MEDIUM,1.000000,0.644498,0.75,1.00